version: '3'

services:
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    # command: "npm run build"
    volumes:
      - /app/node_modules
      - ./:/app
